version: "2"
services:
    mongodb:
        image: mongo:latest
        ports:
          - "27017:27017"
        volumes:
          - /Users/cchadha2/Documents/Github-Private/ieee_fraud/validation/fields.txt:/data/fields.txt
    mongo-seed:
        build:
          context: .
          dockerfile: mongo.Dockerfile
        links:
          - mongodb